src/Entity/Partenaire.php
<?php

namespace App\Entity;

use App\Repository\PartenaireRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;


#[ORM\Entity(repositoryClass: PartenaireRepository::class)]
class Partenaire implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180)]
    private ?string $client_name = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column]
    private ?bool $active = null;

    #[ORM\Column(length: 255)]
    private ?string $short_description = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $full_description = null;

    #[ORM\Column(length: 255)]
    #[Assert\Image(
        minWidth: 100,
        maxWidth: 800,
        maxHeight: 800,
        minHeight: 100,
    )]
    private ?string $logo = null;

    #[ORM\Column(length: 255)]
    private ?string $url = null;

    #[ORM\Column(length: 255)]
    private ?string $dpo = null;

    #[ORM\Column(length: 255)]
    private ?string $technical_contact = null;

    #[ORM\Column(length: 255)]
    private ?string $commercial_contact = null;

    #[ORM\OneToMany(mappedBy: 'client_id', targetEntity: Structure::class)]
    private Collection $structures;

    #[ORM\Column(length: 255, unique: true)]
    private ?string $email = null;

    public function __construct()
    {
        $this->structures = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getClientName(): ?string
    {
        return $this->client_name;
    }

    public function setClientName(string $client_name): self
    {
        $this->client_name = $client_name;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->client_name;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        $roles[] = 'ROLE_PARTENAIRE';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function isActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(bool $active): self
    {
        $this->active = $active;

        return $this;
    }

    public function getShortDescription(): ?string
    {
        return $this->short_description;
    }

    public function setShortDescription(string $short_description): self
    {
        $this->short_description = $short_description;

        return $this;
    }

    public function getFullDescription(): ?string
    {
        return $this->full_description;
    }

    public function setFullDescription(string $full_description): self
    {
        $this->full_description = $full_description;

        return $this;
    }

    public function getLogo(): ?string
    {
        return $this->logo;
    }

    public function setLogo(string $logo): self
    {
        $this->logo = $logo;

        return $this;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(string $url): self
    {
        $this->url = $url;

        return $this;
    }

    public function getDpo(): ?string
    {
        return $this->dpo;
    }

    public function setDpo(string $dpo): self
    {
        $this->dpo = $dpo;

        return $this;
    }

    public function getTechnicalContact(): ?string
    {
        return $this->technical_contact;
    }

    public function setTechnicalContact(string $technical_contact): self
    {
        $this->technical_contact = $technical_contact;

        return $this;
    }

    public function getCommercialContact(): ?string
    {
        return $this->commercial_contact;
    }

    public function setCommercialContact(string $commercial_contact): self
    {
        $this->commercial_contact = $commercial_contact;

        return $this;
    }

    /**
     * @return Collection<int, Structure>
     */
    public function getStructures(): Collection
    {
        return $this->structures;
    }

    public function addStructure(Structure $structure): self
    {
        if (!$this->structures->contains($structure)) {
            $this->structures->add($structure);
            $structure->setClientId($this);
        }

        return $this;
    }

    public function removeStructure(Structure $structure): self
    {
        if ($this->structures->removeElement($structure)) {
            // set the owning side to null (unless already changed)
            if ($structure->getClientId() === $this) {
                $structure->setClientId(null);
            }
        }

        return $this;
    }
    public function __toString()
    {
        return $this->client_name;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

}

src/Entity/Permission.php
<?php

namespace App\Entity;

use App\Repository\PermissionRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PermissionRepository::class)]
class Permission
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?bool $send_newsletter = null;

    #[ORM\Column]
    private ?bool $sell_drink = null;

    #[ORM\Column]
    private ?bool $payment_stats = null;

    #[ORM\Column]
    private ?bool $add_members = null;

    #[ORM\Column]
    private ?bool $recrut_employee = null;

    #[ORM\Column]
    private ?bool $activated_website = null;

    #[ORM\Column]
    private ?bool $place_search = null;

    #[ORM\Column]
    private ?bool $restaurant_site = null;

    #[ORM\Column]
    private ?bool $renovation = null;

    #[ORM\Column]
    private ?bool $available_coach = null;

    #[ORM\Column(length: 255)]
    private ?string $street = null;

    #[ORM\ManyToOne(inversedBy: 'permissions')]
    private ?Structure $branch_id = null;

    #[ORM\Column]
    private ?bool $isActive = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function isSendNewsletter(): ?bool
    {
        return $this->send_newsletter;
    }

    public function setSendNewsletter(bool $send_newsletter): self
    {
        $this->send_newsletter = $send_newsletter;

        return $this;
    }

    public function isSellDrink(): ?bool
    {
        return $this->sell_drink;
    }

    public function setSellDrink(bool $sell_drink): self
    {
        $this->sell_drink = $sell_drink;

        return $this;
    }

    public function isPaymentStats(): ?bool
    {
        return $this->payment_stats;
    }

    public function setPaymentStats(bool $payment_stats): self
    {
        $this->payment_stats = $payment_stats;

        return $this;
    }

    public function isAddMembers(): ?bool
    {
        return $this->add_members;
    }

    public function setAddMembers(bool $add_members): self
    {
        $this->add_members = $add_members;

        return $this;
    }

    public function isRecrutEmployee(): ?bool
    {
        return $this->recrut_employee;
    }

    public function setRecrutEmployee(bool $recrut_employee): self
    {
        $this->recrut_employee = $recrut_employee;

        return $this;
    }

    public function isActivatedWebsite(): ?bool
    {
        return $this->activated_website;
    }

    public function setActivatedWebsite(bool $activated_website): self
    {
        $this->activated_website = $activated_website;

        return $this;
    }

    public function isPlaceSearch(): ?bool
    {
        return $this->place_search;
    }

    public function setPlaceSearch(bool $place_search): self
    {
        $this->place_search = $place_search;

        return $this;
    }

    public function isRestaurantSite(): ?bool
    {
        return $this->restaurant_site;
    }

    public function setRestaurantSite(bool $restaurant_site): self
    {
        $this->restaurant_site = $restaurant_site;

        return $this;
    }

    public function isRenovation(): ?bool
    {
        return $this->renovation;
    }

    public function setRenovation(bool $renovation): self
    {
        $this->renovation = $renovation;

        return $this;
    }

    public function isAvailableCoach(): ?bool
    {
        return $this->available_coach;
    }

    public function setAvailableCoach(bool $available_coach): self
    {
        $this->available_coach = $available_coach;

        return $this;
    }

    public function getStreet(): ?string
    {
        return $this->street;
    }

    public function setStreet(string $street): self
    {
        $this->street = $street;

        return $this;
    }

    public function getBranchId(): ?Structure
    {
        return $this->branch_id;
    }

    public function setBranchId(?Structure $branch_id): self
    {
        $this->branch_id = $branch_id;

        return $this;
    }

    public function isIsActive(): ?bool
    {
        return $this->isActive;
    }

    public function setIsActive(bool $isActive): self
    {
        $this->isActive = $isActive;

        return $this;
    }
    public function toArray() {
        return [
            'id' => $this->getId(),
            'send_newsletter' => $this->isSendNewsletter(),
            'sell_drink' => $this->isSellDrink(),
            'payment_stats' => $this->isPaymentStats(),
            'add_members' => $this->isAddMembers(),
            'recrut_employee' => $this->isRecrutEmployee(),
            'activated_website' => $this->isActivatedWebsite(),
            'place_search' => $this->isPlaceSearch(),
            'restaurant_site' => $this->isRestaurantSite(),
            'renovation' => $this->isRenovation(),
            'available_coach' => $this->isAvailableCoach(),
            'isActive' => $this->isIsActive(),
        ];
    }
}

src/Entity/Structure.php
<?php

namespace App\Entity;

use App\Repository\StructureRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;


#[ORM\Entity(repositoryClass: StructureRepository::class)]
class Structure implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\Column(nullable: true)]
    private ?int $install_id = null;

    #[ORM\Column]
    private ?bool $active = null;

    #[ORM\ManyToOne(inversedBy: 'structures')]
    private ?Partenaire $client_id = null;

    #[ORM\Column(length: 255)]
    private ?string $city = null;

    #[ORM\OneToMany(mappedBy: 'branch_id', targetEntity: Permission::class)]
    private Collection $permissions;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column]
    private array $roles = [];


    #[Assert\Image(
        minWidth: 200,
        maxWidth: 1200,
        maxHeight: 1200,
        minHeight: 200,
    )]
    #[ORM\Column(length: 255, nullable: true)]
    private ?string $logoStructure = null;

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    public function __construct()
    {
        $this->permissions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getInstallId(): ?int
    {
        return $this->install_id;
    }

    public function setInstallId(?int $install_id): self
    {
        $this->install_id = $install_id;

        return $this;
    }

    public function isActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(bool $active): self
    {
        $this->active = $active;

        return $this;
    }

    public function getClientId(): ?Partenaire
    {
        return $this->client_id;
    }

    public function setClientId(?Partenaire $client_id): self
    {
        $this->client_id = $client_id;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    /**
     * @return Collection<int, Permission>
     */
    public function getPermissions(): Collection
    {
        return $this->permissions;
    }

    public function addPermission(Permission $permission): self
    {
        if (!$this->permissions->contains($permission)) {
            $this->permissions->add($permission);
            $permission->setBranchId($this);
        }

        return $this;
    }

    public function removePermission(Permission $permission): self
    {
        if ($this->permissions->removeElement($permission)) {
            // set the owning side to null (unless already changed)
            if ($permission->getBranchId() === $this) {
                $permission->setBranchId(null);
            }
        }

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getLogoStructure(): ?string
    {
        return $this->logoStructure;
    }

    public function setLogoStructure(?string $logoStructure): self
    {
        $this->logoStructure = $logoStructure;

        return $this;
    }
    public function __toString()
    {
        return $this->name;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }
    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        $roles[] = 'ROLE_STRUCTURE';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

}

templates/structure/partenaire-id.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{title}}{% endblock %}

{% block body %}

<div class="panel">
    <h1>Votre sociétée : </h1>
    <div class="tableEntreprise">
        <table class="table">
            <thead>
            <tr>
                <th scope="col" id="lienInterne1">Nom de la franchise :  </th>
                <th scope="col" style="font-size: xxx-large"><u>{{ partenaire.clientName }}</u></th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <th>Entreprise active ? </th>
                <th> {{ partenaire.active }}</th>
            </tr>
            <tr>
                <th>Description rapide  </th>
                <th> {{ partenaire.shortDescription }}</th>
            </tr>
            <tr>
                <th>Descirption complète </th>
                <th>{{ partenaire.fullDescription }}</th>
            </tr>
            <tr>
                <th>Logo </th>
                <th>    <img src="{{ asset('picture/recipe-picture/' ~ partenaire.getLogo()) }}" alt="Image du logo de l'entreprise">
                </th>
            </tr>
            <tr>
                <th>Site de l'entreprise</th>
                <th>{{ partenaire.url }}</th>
            </tr>
            <tr>
                <th>Politique de confidentialitée</th>
                <th>  {{ partenaire.dpo }}</th>
            </tr>
            <tr>
                <th>Numero du technicien </th>
                <th><a href="tel:0606060606"> {{ partenaire.technicalContact }}</a></th>
            </tr>
            <tr>
                <th>Numero du commercial</th>
                <th> <a href="tel:0607070707">{{ partenaire.commercialContact }}</a></th>
            </tr>
            <tr>
                <th>Nombre de structure possédées</th>
                <th> <a href="{{ path('app_liste_structure_partenaire') }}">{{ partenaire.structures.count }}</a></th>
            </tr>
            <tr>
                <th>Nombre de bâtiments possédés en France</th>
                <th> <a href="{{ path('app_liste_permissions_partenaire') }}">{{ permission }}</a></th>
            </tr>
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

templates/structure/structure-id.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{title}}{% endblock %}

{% block body %}
    <h1>{{ structure.name }}</h1>
    <div class="structureId">
         <img src="{{ asset('picture/recipe-picture/' ~ structure.getLogoStructure()) }} " class="card-img-top" alt="Image de la structure">
         <div class="barreHorizontale"></div>
        <h2>Franchise : {{ structure.clientId }}</h2>
        <h3>Coordronnées de la structure: </h3>
            <ul>
                <li>Ville : {{ structure.city }}</li>
                <li>Nom de la structure : {{ structure.name }}</li>
                <li style="color: red; font-weight: bold;">En activitée : {{ structure.active ? 'Oui' : 'Non'}}</li>
                <li>Email du gérant : {{ structure.email }}</li>
                <br>
            </ul>
        {% if app.user.roles == ['ROLE_ADMIN'] %}
        <div class="buttonModif">
        <button type="button" class="buttonSend"><a href="{{ path('app_update_structure', {'id' : structure.id }) }}"> Modifier la structure</a></button>
        <button type="button"
                class="buttonSend">
            <a href="{{ path('app_delete_structure', {'id': structure.id}) }}"> Supprimer la structure
            </a>
        </button>
        </div>
        {% endif %}
        <br>
    </div>
    <h2 style="color:#DEDEDE; text-align: center; margin-top: 4%;">Bâtiments que posséde la structure: </h2>
    <div class="structureId">
    {% for permission in permissions %}
            {% if permission.branchId == structure %}
            <div class="listePermissions">
                <h3><u>Adresse</u> : {{ permission.street }}</h3>
                <ul>
                    <li>Envoyer newsletter : {{ permission.sendNewsletter ? 'Oui' : 'Non' }}</li>
                    <li>Vendre boissons : {{ permission.sellDrink ? 'Oui' : 'Non' }}</li>
                    <li>Voir stats paiement	: {{ permission.paymentStats ? 'Oui' : 'Non' }}</li>
                    <li>Ajouter membre : {{ permission.addMembers ? 'Oui' : 'Non' }}</li>
                    <li>Recruter sallarier : {{ permission.recrutEmployee ? 'Oui' : 'Non' }}</li>
                    <li>Site activé : {{ permission.activatedWebsite ? 'Oui' : 'Non' }}</li>
                    <li>Recherche nouveau lieu : {{ permission.placeSearch ? 'Oui' : 'Non' }}</li>
                    <li>Restaurant sur place : {{ permission.restaurantSite ? 'Oui' : 'Non' }}</li>
                    <li>Renauvation à pervoire : {{ permission.renovation ? 'Oui' : 'Non' }}</li>
                    <li>Coach disponible : {{ permission.availableCoach ? 'Oui' : 'Non' }}</li>
                    <li style="color:red;"> <b>Structure en activité ? {{ permission.isActive ? 'Oui' : 'Non' }}</b></li>
                </ul>
                {% if app.user.roles == ['ROLE_ADMIN'] %}
                    <div class="buttons">
                    <button type="button"
                            class="buttonSend">
                        <a href="{{ path('app_update_permission', {'id': permission.id}) }}"> Accés aux modifs. du Bâtiment
                        </a>
                    </button>
                        <button type="button"
                                class="buttonSend">
                            <a href="{{ path('app_delete_permission', {'id': permission.id}) }}"> Supprimer Bâtiment
                            </a>
                        </button>
                    <button type="button" class="buttonSend"><a href="{{ path('app_permission', {'id': permission.id}) }}">Accés au bâtiment</a></button>
                    </div>
                        <br>
                    {% else %}
                        <button type="button" class="buttonSend"><a href="{{ path('app_permission', {'id': permission.id}) }}">Accés au bâtiment</a></button>
                        <br>
                {% endif %}
                <div class="barreHorizontale"></div>
                <br>
            </div>
            {% endif %}
        {% endfor %}
    </div>

{% endblock %}

templates/structure/structure-partenaire.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{title}}{% endblock %}

{% block body %}
    <h1>{{ structure.name }}</h1>
    <div class="structureId">
        <img src="{{ asset('picture/recipe-picture/' ~ structure.getLogoStructure()) }} " class="card-img-top" alt="Image de la structure">
        <div class="barreHorizontale"></div>
        <h2>Franchise : {{ structure.clientId }}</h2>
        <h3>Coordronnées de la structure: </h3>
        <ul>
            <li>Ville : {{ structure.city }}</li>
            <li>Nom de la structure : {{ structure.name }}</li>
            <li style="color: red; font-weight: bold;">En activitée : {{ structure.active ? 'Oui' : 'Non'}}</li>
            <li>Email du gérant : {{ structure.email }}</li>
            <br>
        </ul>
        {% if app.user.roles == ['ROLE_ADMIN'] %}
            <div class="buttonModif">
                <button type="button" class="buttonSend"><a href="{{ path('app_update_structure', {'id' : structure.id }) }}"> Modifier la structure</a></button>
                <button type="button"
                        class="buttonSend">
                    <a href="{{ path('app_delete_structure', {'id': structure.id}) }}"> Supprimer la structure
                    </a>
                </button>
            </div>
        {% endif %}
        <br>
    </div>
    <h2 style="color:#DEDEDE; text-align: center; margin-top: 4%;">Bâtiments que posséde la structure: </h2>
    <div class="structureId">
        {% for permission in permissions %}
            {% if permission.branchId == structure %}
                <div class="listePermissions">
                    <h3><u>Adresse</u> : {{ permission.street }}</h3>
                    <ul>
                        <li>Envoyer newsletter : {{ permission.sendNewsletter ? 'Oui' : 'Non' }}</li>
                        <li>Vendre boissons : {{ permission.sellDrink ? 'Oui' : 'Non' }}</li>
                        <li>Voir stats paiement	: {{ permission.paymentStats ? 'Oui' : 'Non' }}</li>
                        <li>Ajouter membre : {{ permission.addMembers ? 'Oui' : 'Non' }}</li>
                        <li>Recruter sallarier : {{ permission.recrutEmployee ? 'Oui' : 'Non' }}</li>
                        <li>Site activé : {{ permission.activatedWebsite ? 'Oui' : 'Non' }}</li>
                        <li>Recherche nouveau lieu : {{ permission.placeSearch ? 'Oui' : 'Non' }}</li>
                        <li>Restaurant sur place : {{ permission.restaurantSite ? 'Oui' : 'Non' }}</li>
                        <li>Renauvation à pervoire : {{ permission.renovation ? 'Oui' : 'Non' }}</li>
                        <li>Coach disponible : {{ permission.availableCoach ? 'Oui' : 'Non' }}</li>
                        <li style="color:red;"> <b>Structure en activité ? {{ permission.isActive ? 'Oui' : 'Non' }}</b></li>
                    </ul>
                    {% if app.user.roles == ['ROLE_ADMIN'] %}
                        <div class="buttons">
                            <button type="button"
                                    class="buttonSend">
                                <a href="{{ path('app_update_permission', {'id': permission.id}) }}"> Accés aux modifs. du Bâtiment
                                </a>
                            </button>
                            <button type="button"
                                    class="buttonSend">
                                <a href="{{ path('app_delete_permission', {'id': permission.id}) }}"> Supprimer Bâtiment
                                </a>
                            </button>
                            <button type="button" class="buttonSend"><a href="{{ path('app_permission', {'id': permission.id}) }}">Accés au bâtiment</a></button>
                        </div>
                        <br>
                    {% else %}
                        <button type="button" class="buttonSend"><a href="{{ path('app_permission', {'id': permission.id}) }}">Accés au bâtiment</a></button>
                        <br>
                    {% endif %}
                    <div class="barreHorizontale"></div>
                    <br>
                </div>
            {% endif %}
        {% endfor %}
    </div>

{% endblock %}

templates/structure/structure-structure.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{title}}{% endblock %}

{% block body %}
    <h1>{{ structure.name }}</h1>
    <div class="structureId">
        <img src="{{ asset('picture/recipe-picture/' ~ structure.getLogoStructure()) }} " class="card-img-top" alt="Image de la structure">
        <div class="barreHorizontale"></div>
        <h2>Franchise : {{ structure.clientId }}</h2>
        <h3>Coordronnées de la structure: </h3>
        <ul>
            <li>Ville : {{ structure.city }}</li>
            <li>Nom de la structure : {{ structure.name }}</li>
            <li style="color: red; font-weight: bold;">En activitée : {{ structure.active ? 'Oui' : 'Non'}}</li>
            <li>Email du gérant : {{ structure.email }}</li>
            <br>
        </ul>
        {% if app.user.roles == ['ROLE_ADMIN'] %}
            <div class="buttonModif">
                <button type="button" class="buttonSend"><a href="{{ path('app_update_structure', {'id' : structure.id }) }}"> Modifier la structure</a></button>
                <button type="button"
                        class="buttonSend">
                    <a href="{{ path('app_delete_structure', {'id': structure.id}) }}"> Supprimer la structure
                    </a>
                </button>
            </div>
        {% endif %}
        <br>
    </div>
    <h2 style="color:#DEDEDE; text-align: center; margin-top: 4%;">Bâtiments que posséde la structure: </h2>
    <div class="structureId">
        {% for permission in permissions %}
            {% if permission.branchId == structure %}
                <div class="listePermissions">
                    <h3><u>Adresse</u> : {{ permission.street }}</h3>
                    <ul>
                        <li>Envoyer newsletter : {{ permission.sendNewsletter ? 'Oui' : 'Non' }}</li>
                        <li>Vendre boissons : {{ permission.sellDrink ? 'Oui' : 'Non' }}</li>
                        <li>Voir stats paiement	: {{ permission.paymentStats ? 'Oui' : 'Non' }}</li>
                        <li>Ajouter membre : {{ permission.addMembers ? 'Oui' : 'Non' }}</li>
                        <li>Recruter sallarier : {{ permission.recrutEmployee ? 'Oui' : 'Non' }}</li>
                        <li>Site activé : {{ permission.activatedWebsite ? 'Oui' : 'Non' }}</li>
                        <li>Recherche nouveau lieu : {{ permission.placeSearch ? 'Oui' : 'Non' }}</li>
                        <li>Restaurant sur place : {{ permission.restaurantSite ? 'Oui' : 'Non' }}</li>
                        <li>Renauvation à pervoire : {{ permission.renovation ? 'Oui' : 'Non' }}</li>
                        <li>Coach disponible : {{ permission.availableCoach ? 'Oui' : 'Non' }}</li>
                        <li style="color:red;"> <b>Structure en activité ? {{ permission.isActive ? 'Oui' : 'Non' }}</b></li>
                    </ul>
                    {% if app.user.roles == ['ROLE_ADMIN'] %}
                        <div class="buttons">
                            <button type="button"
                                    class="buttonSend">
                                <a href="{{ path('app_update_permission', {'id': permission.id}) }}"> Accés aux modifs. du Bâtiment
                                </a>
                            </button>
                            <button type="button"
                                    class="buttonSend">
                                <a href="{{ path('app_delete_permission', {'id': permission.id}) }}"> Supprimer Bâtiment
                                </a>
                            </button>
                            <button type="button" class="buttonSend"><a href="{{ path('app_permission', {'id': permission.id}) }}">Accés au bâtiment</a></button>
                        </div>
                        <br>
                    {% else %}
                        <button type="button" class="buttonSend"><a href="{{ path('app_permission_structure', {'id': permission.id}) }}">Accés au bâtiment</a></button>
                        <br>
                    {% endif %}
                    <div class="barreHorizontale"></div>
                    <br>
                </div>
            {% endif %}
        {% endfor %}
    </div>

{% endblock %}